### ISSUE TITLE
Webhook block specification

### ISSUE THREAD

**Issue by ggiraldez** [FLOIP/flow-spec#24]
Initial outline to kick off the discussion.

The webhook block will define an HTTP call to an external service. We need to define how the block will behave and what are the required parameters to configure it.

This is not a generic HTTP block but rather a specific ‘interface with services that play well with FLOW’ block. 

What has worked for us very well is the notion of a manifest that declares specific blocks based on services that can then be put in flows. See https://github.com/instedd/verboice/wiki/External-Services

Example:

```yml
results:
  displayName: Analysis Results
  icon: medicalkit
  type: callback
  callbackUrl: http://{service_domain}/results
  settings:
    -
      name: pin
      displayName: Patient ping
      type: string
  response:
    -
      name: result
      displayName: Result
      type: string
```

## Configuration

 * **URL:** Either a string with interpolation or a raw expression. There may to be a 'global' constant value provided by the tool with the base URL of the service and each block will construct the service URL from it.
 * **HTTP verb**: POST required, GET suggested. We may want to support PUT, PATCH and DELETE later.
 * **Authentication credentials**: Services need to authenticate. Credentials may be defined outside the scope of the flow, but we need to be able to reference them from the flow, or be bound to the service URL. Support OAuth2 tokens and HTTP basic.
 * **Parameters**: A map from parameter name to an expression. Query or POST body? Or both? Query string works for any HTTP verb but it's limited in size (depending on the server implementation). POST body will not work for GET. Let’s choose one and use the other as optional.
 * **Extra HTTP headers**. Optional, but can be very useful. Same as parameters, a map from name to expressions.
 * **Timeout** waiting for the response.

## Behaviour

 * **Synchronous/asynchronous** mode. A service can declare it is one-way-able. In this case, requests can be queued for offline operation. Do we specify ordering guarantees or leave it up to each implementation?
 * **Mimetype** of the response. Support JSON at a minimum. Add XML and plain text later.
 * **Follow redirects**. This is probably a given, but needs to be specified. Allows e.g. Google scripts APIs and other sort of frameworks to be used.
 * **Cookie handling**. Optional. Can be used to establish a session with the service (eg. for authentication). We may want to define different scopes, eg. use different cookie jars depending on flow/contact/session.
 * **Mapping of results**, ie. how to parse the result and put it in the context. Use JSONPath (or a subset) to reference data in a JSON response. We want (a subset of) XPath if we support XML responses.
